### ISSUE TITLE
Distribution plans

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#108]
I thought it might be worth discussing what our plans for distribution are at this point.  The document is in pretty good shape, and with the semester starting soon, it would be nice to get the book out there.  For my students, I plan to compile a pdf without solutions, hints in the back, and post it on my LMS.  I will also publish a html version through my website, but not advertised widely (maybe with no splash page).   

It wouldn't be too much work to run the pdf through createspace to make a print edition available (which would allow student to get a printed copy much cheaper than printing themselves.  But before we do that, we should agree on #90.   We can always update things like cover art.  (I don't think I'm going to worry about this for my 7 students, who can just print the pdf using our math department's copier, but for others?)

Also, we probably need to put a copy of the licence inside the pdf somewhere, right?

**Comment by mitchkeller** [comment]
Yeah, we'll need to set something up either through GitHub.io or on one of our websites to distribute this. And let Dartmouth know we've done it so they can link to it (or not, at their option) once it's officially public and ready for use. I think a CreateSpace edition would be nice, and also easy since you and I both have experience with it. We could use royalties to pay for a domain name to host the book under, too, and then it could be moved as necessary over time but the public would always get at it from the same place. I am hoping to give a talk to one of the IBL sessions at JMM about the book and PTX in general to help broaden the reach and get people in that community thinking about licensing and such, so having a hard copy to show off and tell people they can get it would be nice. If we have royalties beyond the domain name, we'll have to think about what to do with them. Scholarship fund at Dartmouth? Academy for Inquiry-Based Learning in Mathematics? AIM Open Textbooks Initiative (perhaps to buy copies of various books to give away at JMM and MathFest)?

**Comment by oscarlevin** [comment]
I've secured "openmathbooks.org", which I plan to host my discrete book on, as well as anyone else's who doesn't want to buy a domain name.  I've forked my copy of ibl-combinatorics to github.com/OpenMathBooks, and will put the html version there for now, and eventually redirect bogart.openmathbooks.org to it.  

Unless you think this is a poor idea.

**Comment by mitchkeller** [comment]
Sounds like a good idea to me.

**Comment by mitchkeller** [comment]
I'm going to close this, since I think we've resolved everything on here. Reopen if you see something that we need to keep discussing here (instead of on #114).
