### ISSUE TITLE
Missing merged pull request

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#71]
I was going to add a few tikz images to appendix A.1.3 and thought I would base what I do on the digraphs I added back in #35.  However, for some reason, this pull request seems to have been undone (or overwritten, or something).  This pull request also fixed all of the `{n \choose k}` and `{1 \over 2}` problems we had.

Do either of you know how to get these commits back without messing everything up?

**Comment by oscarlevin** [comment]
It looks like the work in Section 1.2 was undone in commit 1eb0fc4545b2cd3e3379709c229b183b3b646fee, merged in #36

**Comment by mitchkeller** [comment]
It looks like the *only* file that got mucked up along the way is s1-2-basics.mbx, since that's the only file that I find \over or \choose in. I think you can checkout the commit hash for where you added in the  stuff you want and then use that to get back the bits and bobs needed. It seems that "Work on 1-2" is where things went awry for that file, if you look at the [history for it](https://github.com/oscarlevin/ibl-combinatorics/commits/ee4cbf5fca4bdc84c3c45250cd7ed534a388f512/mbx/s1-2-basics.mbx)

**Comment by oscarlevin** [comment]
In that case, I will copy over the three images by hand and do a find/replace on the \choose/\over bits.

**Comment by mitchkeller** [comment]
That seems like a reasonable approach. Looks like a failure to rebase before the PR that did the reversion combined with the very precise differences making it look like those changes were intentional caused this to be missed when it happened. At least (a) we've got the file to go back to and (b) it's just that file.
