### ISSUE TITLE
Add pretty formatting for pdf version

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#88]
A few things can be done to improve the look of the book. 

1. We can change the font, headings, margins, etc.
2. We can format the problem environment to make it stand out from the text a bit (right now, with hints and solutions mixed in, it is hard to see where one thing stops and the next starts).
3. Where should hints and solutions go?  If we want to put one or both in the backmatter, we can automatically create hyperlinks between them and the problems.
4. Something else?

**Comment by mitchkeller** [comment]
1. I'm good with pretty much whatever here.
1. It would at least be nice to have an "end of solution" mark like the official PDF does.
1. For HTML, I think it would be best to have hints in knowls with the problems and solutions in backmatter. (I know this issues is about PDF, but I wanted to put that thought somewhere.) For PDF, I think backmatter for both is a good idea. One backmatter item for hints and another for solutions. Part of why Bogart put the hints online was so that students would have to take an extra step to look up a hint.

**Comment by oscarlevin** [comment]
Come to think of it, do we want to have solutions anywhere at all?  I mean for the student version.  It would be nice to have an instructor edition with full solutions, but maybe they are put in the main text (along with the hints).

**Comment by mitchkeller** [comment]
I would be very happy to have the HTML version and the very public PDF have no solutions. (Hints knowled in HTML and in backmatter in PDF.) We can make a PDF with hints and solutions inline for email distribution to instructors.

Yes, the solutions are all in the GitHub repo, but going in there to find and read them requires a fair bit of industriousness on the part of students, and so not having the solutions anywhere in the general version sounds great to me.

One thing to consider longer term would be to take the *answers* to problems that have a concise numerical-ish answer and put them inside answer tags, since I do think that it's nice for students to have the answers to the motivational problems as a way to check themselves. But that's a project for later, at least in my mind.

**Comment by oscarlevin** [comment]
This sounds good to me.  I'll use the book in my graduate class starting Monday, and will make a version as you suggest.

Incidentally, I don't quite agree with your assessment of the industriousness needed by students to find solutions.  A few semester's back, I found students were able to google the statement of a problem in my book and find the github repo with solution right next to it.

**Comment by mitchkeller** [comment]
Me, overly idealistic and naïve? Never!

At least with this project, the solutions were put out there by someone else years ago, so we don't need to engage in handwringing about it, but we can do our part to make students be industrious in order to get ahold of the solutions.

I still haven't put my book's solutions in my repo. Alex and I were chatting in Tacoma about some script-fu that would automagically encrypt/decrypt answers and solutions so that they could be stored on GitHub. Requires lots of author discipline to never do a commit with the solutions decrypted, and so maybe only a power user solution, but I'm intrigued and may give it a try this fall. (I'm on sabbatical until January, so will have some time to contemplate such things when my brain is in that state where it's too tired of real math to do any more for the day.)

**Comment by mitchkeller** [comment]
Now that we've got hint markers in the body, I'm going to call this one done. As I wrote on #114, the hyperlinks from problems to their hints aren't crucial, since people are unlikely to be using the PDF in that way (versus using HTML).
