### ISSUE TITLE
Minor annoyance regarding parts references

### ISSUE THREAD

**Issue by oscarlevin** [OpenDiscreteMath/ibl-combinatorics#99]
This isn't a big deal, but might be nice to fix, either ourselves or to bug Rob on the ptx forums: right now, we you reference a part locally, say with `<xref ref="thepart" text="type-local" /> you get "Part a" (assuming "thepart" is really the first part of the problem).  I would prefer this be printed as "Part (a)".  

Is this worth worrying about now?

**Comment by mitchkeller** [comment]
I'd say file an issue for Rob on it but declare it not urgent. I agree that it would be nice to fix, but it's not a deal breaker to me. To me, it's similar to the idea that if I reference a task outside of its containing activity, I would prefer to get "part (c) of Problem 183" than "part 183.c" or "Problem 183.c" I'd like to be able to get that long phrase version without having to manually construct it with two `xref`s, perhaps by adding a new value for `@text` on `xref`. Maybe the issue needs to be about references to tasks in general so that there's room for a few things to be dealt with together.

**Comment by oscarlevin** [comment]
Issue filed with Rob, which will get this fixed eventually.
